### ISSUE TITLE
Feature Request: Add xtask file contents as a url param (compressed or whatever)

### ISSUE THREAD

**Issue by greggiacovelli** [scottyob/paragliding-task-checker#1]
Just suggesting to allow passing a url around for a task after.

so for example the following task:

    {
     "version": 1,
     "taskType": "CLASSIC",
     "turnpoints": [
          {
               "radius": 1800,
               "waypoint": {
                    "lon": -119.37335555555555,
                    "lat": 37.015507,
                    "altSmoothed": 1241,
                    "name": "POINTLN",
                    "description": "Some Launch"
               },
               "type": "SSS"
          },
          {
               "radius": 400,
               "waypoint": {
                    "lon": -119.38660555555556,
                    "lat": 37.033307,
                    "altSmoothed": 1190,
                    "name": "TP1",
                    "description": "SOME POINT"
               }
          },
          {
               "radius": 400,
               "waypoint": {
                    "lon": -119.456675,
                    "lat": 37.065124999999995,
                    "altSmoothed": 645,
                    "name": "TP2",
                    "description": "SOMEPOINT2"
               }
          },
          {
               "radius": 3000,
               "waypoint": {
                    "lon": -119.38660555555556,
                    "lat": 37.03330833333333,
                    "altSmoothed": 1190,
                    "name": "TP1",
                    "description": "SOME POINT"
               }
          },
          {
               "radius": 400,
               "waypoint": {
                    "lon": -119.46508888888889,
                    "lat": 37.073888888888895,
                    "altSmoothed": 930,
                    "name": "TP3",
                    "description": "SOME OTHER POINT"
               }
          },
          {
               "radius": 2000,
               "waypoint": {
                    "lon": -119.4003888888889,
                    "lat": 37.01400833333334,
                    "altSmoothed": 581,
                    "name": "TP4",
                    "description": "SOMEPLACE"
               },
               "type": "ESS"
          },
          {
               "radius": 400,
               "waypoint": {
                    "lon": -119.4003888888889,
                    "lat": 37.01400833333334,
                    "altSmoothed": 581,
                    "name": "TP4",
                    "description": "SOMEPLACE"
               }
          }
     ],
     "sss": {
          "type": "RACE",
          "direction": "EXIT",
          "timeGates": [
               "20:15:00Z"
          ]
     },
     "goal": {
          "type": "CYLINDER",
          "deadline": "23:00:00Z"
     },
     "earthModel": "WGS84"
    }

Could be compressed and base64'd to produce something like:
`H4sICNrzQWIAA3NvbWUtdGFzay54Y3RzawC901trgzAUAOD3/Ypynl1JjPH2Vpx0gm1HI+xGH0INq8xLUbtRiv990dnWtVLKYDtPenI5X45xBx8iL6IsBRsrUPLiPdiuBdjg+CPGPAdkcpOn6yxKywLs1x3kPIw28hGbCCnwybfNGNg7iOtdbjG2hsQghB5CgZjLCcQYIkwpMhTgccmSLCtXIpQbqZosnfKkLvsw86aBP5VlQ1Es82hdNjZgWSIGPt+kyxVU0vSNZIzJt6NJu0AydR3tRXqHRAg5J2ELHUjBAz7nzCbuoLFCdSVAo7pudHuhU3lyqw16ItA12gGovYCmvvoTQNAvW2CSNv6jFTpF5j6sDsQg5jF/2hKLdCGkHzIL7t15H0e90BhJJX0cLAf2fdFONNTEHY3W/4H8keN2rqt7/XX9Y1K1UKAoirpma5vXebkiysWyne8+eUH9/0eJGPNS1L8/qMjG1EboBRbyXG8Zjzt7OM++N71z501lHsZRWmdVIuc3S+QKwfNyNclCIdfB45iZGlQ3X1Yx2neFBAAA`

That way we could share the url with the task embedded

or simply convert to v2 and embedd that minimal format to the url. Either way we do it, I could definitely see this as a useful feature among peers at a task or event

**Comment by tris** [comment]
also see "Task definition format 2 - for QR codes":

https://xctrack.org/Competition_Interfaces.html

**Comment by scottyob** [comment]
Totally makes sense.  I'll get to that probably in the next two weeks.  If either of you want to have a crack at it in the mean time, feel free to mention you're working on it then I'll accept pull requests ;)

**Comment by scottyob** [comment]
Solved in https://github.com/scottyob/paragliding-task-checker/commit/72f68971bed4db7feef7cf3b121ec3df6637e8d1
